#	HIDE'N'SEEK DEEP REINFORCEMENT LEARNING CONFIG FILE

#	AUTHORS:
#		- Lechowicz Hubert
#		- Mrosek Dawid
#		- Płaneta Lukasz
#	LICENSE: MIT

#	VIDEO:
#		CENTERED: whenever game window should be centered (0 - no, 1 - yes); works only for `human` render mode
#		DRAW_POV: If Agent POV should be drawn; consumes A LOT of FPS; probably most computation-heavy algorithm
# 	MONITORING: If Environment should be recorded every 100th episode; may decrease FPS only for that episode

#	GAME:
#		EPISODES: Training Episodes
#		FPS: Max Frames Per Second
#		DURATION: Game duration in frames, ends if Seeker don't collide with Hiding
#		REVERSE: If turn order should be reversed (Hiding first instead of Seeker first)
#		MAP: Relative path to map BMP for Map Generator
#		GRAPHICS_PATH_WALL: Relative path to folder with walls made by Map Generator
#		GRAPHICS_PATH_WALL_OWNER: Relative path to folder with walls made by Hiding Agent
#		ALGORITHMS: List of algorithms created by authors, together with its string representation
#		ALGORITHM: Chosen algorithm to train model on

#	SEEKER:
#		SPEED_RATIO: Multiplier for Agent movement (in frames)
#		SPEED_ROTATE_RATIO: Multiplier for Agent rotate angle (in frames)
#		WALL_ACTION_TIMEOUT: Timeout after doing wall-related action (in frames)
#		GRAPHICS_PATH: Relative path to folder with Seeker graphics

#		REWARDS:
#			NOOP: Points for doing nothing
#			MOVE: Points per move (successful)
#			ROTATE: Points per rotate (successful)
#			SPECIAL: Points per deleted Wall (successful)
#			WIN: Points if won the game
#			LOSE: Points if lost the game

#	HIDING:
#		SPEED_RATIO: Multiplier for Agent movement (in frames)
#		SPEED_ROTATE_RATIO: Multiplier for Agent rotate angle (in frames)
#		WALL_ACTION_TIMEOUT: Timeout after doing wall-related action (in frames)
#		WALLS_MAX: Max number of walls created by Agent
#		GRAPHICS_PATH: Relative path to folder with Hiding graphics

# 	REWARDS:
#			NOOP: Points for doing nothing
#			MOVE: Points per move (successful)
#			ROTATE: Points per rotate (successful)
#			SPECIAL: Points per deleted Wall (successful)
#			WIN: Points if won the game
#			LOSE: Points if lost the game

video:
  centered: yes
  draw_pov: no
  monitoring: yes

game:
  episodes: 2000
  fps: 600
  duration: 2000
  reverse: no
  map: maps/map3.bmp
  continuous_reward: no
  graphics_path_wall: graphics/wall/game
  graphics_path_wall_owner: graphics/wall/ai
  algorithms:
    a2c: "A2C"
    dqn: "DQN"
    ppo: "PPO"
  algorithm: a2c

seeker:
  speed_ratio: 5
  speed_rotate_ratio: 0.2
  wall_action_timeout: 50
  graphics_path: graphics/people/policeman
  rewards:
    noop: -1
    move: -1
    rotate: -1
    special: -1
    win: 100
    lose: 100

hiding:
  speed_ratio: 5
  speed_rotate_ratio: 0.2
  wall_action_timeout: 50
  walls_max: 5
  graphics_path: graphics/people/thief
  rewards:
    noop: -1
    move: -1
    rotate: -1
    special: -1
    win: 100
    lose: 100
